### ISSUE TITLE
SMTPAuthenticationError when trying to email results

### ISSUE THREAD

**Issue by cklaassen** [bandsquad/google-trends-fetch#110]
The code throws a SMTPAuthenticationError when the program is trying to email results.  I don't know if this is due to something on Google's end blocking us or something In our program that isn't initiating it correctly.  Due to the limited knowledge I have of email servers, I can't solve this issue.

**Comment by cklaassen** [comment]
`Traceback (most recent call last):
  File "/Users/connorklaassen/Documents/ComputerScience/google-trends-fetch/main.py", line 31, in <module>
    send.run(recipients, subject, body)
  File "/Users/connorklaassen/Documents/ComputerScience/google-trends-fetch/send.py", line 6, in run
    yag.send(to=recipient, subject=title, contents=body)
  File "/usr/local/lib/python3.7/site-packages/yagmail/sender.py", line 144, in send
    self.login()
  File "/usr/local/lib/python3.7/site-packages/yagmail/sender.py", line 243, in login
    self._login(self.credentials)
  File "/usr/local/lib/python3.7/site-packages/yagmail/sender.py", line 201, in _login
    self.smtp.login(self.user, password)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/smtplib.py", line 730, in login
    raise last_exception
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/smtplib.py", line 642, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (534, b'5.7.9 Please log in with your web browser and then try again. Learn more at\n5.7.9  https://support.google.com/mail/?p=WebLoginRequired w3sm7388580pge.8 - gsmtp')`
